/*************************************************************
Proyecto:REQXXXXXX - Migración Trazamat. 
Descripción: Creacion de tablas para BDITKENS.
Parámetros de entrada: 
Parámetros de salida: 
Valor de retorno: N/A
Parámetros de entrada-salida: N/A
Creador: José Alberto Ríos López
Fecha de creación: 29/07/2019
*************************************************************/

USE BDITKENS
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQCATALOGOS.TBCOMPONENTES')
           AND   TYPE = 'U')
   DROP TABLE SQCATALOGOS.TBCOMPONENTES
GO

CREATE TABLE SQCATALOGOS.TBCOMPONENTES(
	FICOMPONENTEID				INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,--BDITKENS
	FCNOMBRE 					VARCHAR(50) 	NOT NULL DEFAULT '-',
	FCDESCRIPCION 				VARCHAR(150) 	NOT NULL DEFAULT '-'
	CONSTRAINT PK_TBCOMPONENTES_01 PRIMARY KEY (FICOMPONENTEID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBCOMPONENTESDESCARGADOS')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBCOMPONENTESDESCARGADOS
GO

CREATE TABLE SQTRAZAMAT.TBCOMPONENTESDESCARGADOS(
	FICOMPONENTEDESCARGADOID	INT 			IDENTITY(1,1).
	FICOMPONENTEID 				INT 			NOT NULL,
	FIMODELOID 					INT 			NOT NULL,--BDITKENS
	FIUSUARIORECIBOID			INT 			NOT NULL,--BDITKENS
	FIUSUARIOCALIDADID			INT 			NOT NULL,--BDITKENS
	FIESTATUSID 				INT 			NOT NULL,--BDITKENS
	FCORDENPEDIDO				VARCHAR(15) 	NOT NULL DEFAULT '-',--SI VA SISLOGIN
	FCORDENPROOVEDOR 			VARCHAR(50)		NOT NULL DEFAULT '-',--SI VA SISLOGIN
	FCNUMBLOQUE 				VARCHAR(50) 	NOT NULL DEFAULT '-',--SI VA SISLOGIN
	FCNUMCONTENEDOR				VARCHAR(50)	    NOT NULL DEFAULT '-',--SI VA SISLOGIN
	FCORDENCANCELADA         	VARCHAR(50)	    NOT NULL DEFAULT '-',--NO SE
	FITOTALCONTENEDORES			INT 			NOT NULL DEFAULT 0,--SI VA SISLOGIN
	FITOTALARMADAS 				INT 			NOT NULL DEFAULT 0,--NO SE
	FICANTIDADPEDIDA 			INT 			NOT NULL DEFAULT 0,--SI VA SISLOGIN
	FIFALTANTES 				INT 			NOT NULL DEFAULT 0,--NO SE
	FICANTIDADRECIBIDA 			INT 			NOT NULL DEFAULT 0,--SI VA KAREN
	FICANTIDAD BLOQUEADA        INT 			NOT NULL DEFAULT 0,--SI VA LEIBINZ
	FICANTIDADLIBERADAQM        INT 			NOT NULL DEFAULT 0,--SI VA LEININZ
	FCMOTIVORECHAZO             VARCHAR(50)		NOT NULL DEFAULT '-',--PUEDE QUE SI
	FIRECIBIENBODEGA 			INT 			NOT NULL DEFAULT 0,--SI VA KAREN
	FICOMPLETERECIBO 			INT 			NOT NULL DEFAULT 0,--SI VA KAREN 
	FICONFIRMERECIBO 			INT 			NOT NULL DEFAULT 0,--NO SE 
	FIRECIBIENCALIDAD 			INT 			NOT NULL DEFAULT 0,--SI VA LEIBINZ
	FICOMPLETECALIDAD 			INT 			NOT NULL DEFAULT 0,--SI VA LEIBINZ
	FDFECHASALIDA 				DATE 			NOT NULL DEFAULT GETDATE(),--SI VA SISLOGIN
	FDFECHAARRIBO 				DATE 			NOT NULL DEFAULT GETDATE(),--SI VA SISLOGIN
	FDFECHAIMPORTACION 			DATE 			NOT NULL DEFAULT GETDATE(),--NO SE 
	FDFECHARECIBO 				DATE 			NOT NULL DEFAULT GETDATE(),--SI VA KAREN
	FDFECHACALIDAD 				DATE 			NOT NULL DEFAULT GETDATE(),--SI VA  LEIBINZ
	FDFECHAMODIFICACION 		DATE 			NOT NULL DEFAULT GETDATE(),--NO SE
	CONSTRAINT PK_TBCOMPONENTESDESCARGADOS_01 PRIMARY KEY (FICOMPONENTEDESCARGADOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO






















IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQCATALOGOS.TBALMACENES')
           AND   TYPE = 'U')
   DROP TABLE SQCATALOGOS.TBPRODUCTOS
GO

CREATE TABLE SQCATALOGOS.TBALMACENES(
	FIALMACENID 				INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FIALMACEN 					INT 			NOT NULL DEFAULT 0,
	FICENTRO					INT 			NOT NULL DEFAULT 0,
	FCDESCRIPCION 				VARCHAR(150) 	NOT NULL DEFAULT '-',
   	CONSTRAINT PK_TBALMACENES_01 PRIMARY KEY (FIALMACENID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBBOMSPORMODELO')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBBOMSPORMODELO
GO

CREATE TABLE SQTRAZAMAT.TBBOMSPORMODELOS(
	FIBOMPORMODELOID			INT 			IDENTITY(1,1),
	FIMODELOID					INT 			NOT NULL,
	FICOMPONENTEID				INT 			NOT NULL,
	FIESTATUSID 				INT 			NOT NULL,
	FIALTERNATIVA 				INT 			NOT NULL DEFAULT 0,
	FCPOSICION					VARCHAR(10)		NOT NULL DEFAULT '-',
	FICANTIDAD 					INT 			NOT NULL DEFAULT 0,
	FIPIVOTE 					INT 			NOT NULL DEFAULT 0,
	FINOINDISPENSABLE 			INT 			NOT NULL DEFAULT 0,
	FDFECHAEXTRACCION			DATE			NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_TBBOMSPORMODELOS_01 PRIMARY KEY (FIBOMPORMODELOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO


IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBCOMPONENTESENALMACENES')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBCOMPONENTESENALMACENES
GO

CREATE TABLE SQTRAZAMAT.TBCOMPONENTESENALMACENES(
	FICOMPONENTEENALMACENID		INT 			IDENTITY(1,1).
	FICOMPONENTEID 				INT 			NOT NULL,
	FIALMACENID 				INT 			NOT NULL,
	FICANTIDAD 					INT 			NOT NULL DEFAULT 0,
	FDFECHAEXTRACCION 			DATE 			NOT NULL GETDATE(),
	CONSTRAINT PK_TBCOMPONENTESENALMACENES_01 PRIMARY KEY (FICOMPONENTEENALMACENID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBCOMPONENTESAPARTADOS')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBCOMPONENTESAPARTADOS
GO

CREATE TABLE SQTRAZAMAT.TBCOMPONENTESAPARTADOS(
	FICOMPONENTEAPARTADOID		INT 			IDENTITY(1,1).
	FICOMPONENTEID 				INT 			NOT NULL,
	FIMODELOID 					INT 			NOT NULL,
	FIUSUARIOID 				INT 			NOT NULL,
	FIESTATUSID 				INT 			NOT NULL,
	FICOMPONENTEAPARTADO		INT 			NOT NULL DEFAULT 0,
	FICONTADORMODELO 			INT 			NOT NULL DEFAULT 0,
	FIREPORTEID 				INT 			NOT NULL DEFAULT 0,
	FICANTIDAD 					INT 			NOT NULL DEFAULT 0,
	FIAPARTADASITK          	INT 			NOT NULL DEFAULT 0,
	FIPIEZANECESARIA			INT 			NOT NULL DEFAULT 0,
	FIALTERNATIVA 				INT 			NOT NULL DEFAULT 0,
	CONSTRAINT PK_TBCOMPONENTESAPARTADOS_01 PRIMARY KEY (FICOMPONENTEAPARTADOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO


IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBGRUPOSCORREO')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBGRUPOSCORREO
GO

CREATE TABLE SQTRAZAMAT.TBGRUPOSCORREO(
	FIGRUPOCORREOID				INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FCNOMBRE 					VARCHAR(50) 	NOT NULL DEFAULT '-',
	FCDESCRIPCION 				VARCHAR(150) 	NOT NULL DEFAULT '-',
	CONSTRAINT PK_TBGRUPOSCORREO_01 PRIMARY KEY (FIGRUPOCORREOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBUSUARIOSXGRUPOSCORREO')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBUSUARIOSXGRUPOSCORREO
GO

CREATE TABLE SQTRAZAMAT.TBUSUARIOSXGRUPOSCORREO(
	FIUSUARIOXGRUPOCORREOID		INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FIGRUPOCORREOID 			INT 			NOT NULL,
	FIUSUARIOID 				INT 			NOT NULL,
	CONSTRAINT PK_TBUSUARIOSXGRUPOSCORREO_01 PRIMARY KEY (FIUSUARIOXGRUPOCORREOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBDEFECTOSPORCOMPONENTE')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBDEFECTOSPORCOMPONENTE
GO

CREATE TABLE SQTRAZAMAT.TBDEFECTOSPORCOMPONENTE(
	FIDEFECTOPORCOMPONENTEID	INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FICOMPONENTEID 				INT 			NOT NULL,
	FIDEFECTOSAPQMID			INT 			NOT NULL,
	FITIPOCOMPONENTEID 			INT 			NOT NULL,
	FICANTIDAD 					INT 			NOT NULL DEFAULT 0,
	FCORDENPEDIDO 				VARCHAR(15)		NOT NULL DEFAULT '-',
	FCNUMBLOQUE 				VARCHAR(50)		NOT NULL DEFAULT '-',
	FCNUMCONTENEDOR				VARCHAR(50)		NOT NULL DEFAULT '-',
	CONSTRAINT PK_TBDEFECTOSPORCOMPONENTE_01 PRIMARY KEY (FIUSUARIOXGRUPOCORREOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBDEFECTOSSAPQM')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBDEFECTOSPORCOMPONENTE
GO

CREATE TABLE SQTRAZAMAT.TBDEFECTOSSAPQM(
	FIDEFECTOSAPQMID			INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FITIPOCOMPONENTEID			INT 			NOT NULL,
	FCNOMBRE					VARCHAR(15) 	NOT NULL DEFAULT '-',
	FCDESCRIPCION 				VARCHAR(150)   	NOT NULL DEFAULT '-',
	CONSTRAINT PK_TBDEFECTOSSAPQM_01 PRIMARY KEY (FIDEFECTOSAPQMID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO


IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBINSPECCIONESXCOMPONENTES')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBINSPECCIONESXCOMPONENTES
GO

CREATE TABLE SQTRAZAMAT.TBINSPECCIONESXCOMPONENTES(
	FIINSPECCIONID				INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FITIPOCOMPONENTEID			INT 			NOT NULL,
	FICOMPONENTEID				INT 			NOT NULL DEFAULT 0,
	CONSTRAINT PK_TBINSPECCIONESXCOMPONENTES_01 PRIMARY KEY (FIINSPECCIONID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO


IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBMODELOSPORUSUARIO')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBMODELOSPORUSUARIO
GO

CREATE TABLE SQTRAZAMAT.TBMODELOSPORUSUARIO(
	FIMODELOPORUSUARIOID		INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FIMODELOID 					INT 			NOT NULL,
	FIUSUARIOID					INT 			NOT NULL,
	CONSTRAINT PK_TBMODELOSPORUSUARIO_01 PRIMARY KEY (FIMODELOPORUSUARIOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO

IF EXISTS (SELECT 1 FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('SQTRAZAMAT.TBTIPOSCOMPONENTESSAP')
           AND   TYPE = 'U')
   DROP TABLE SQTRAZAMAT.TBTIPOSCOMPONENTESSAP
GO

CREATE TABLE SQTRAZAMAT.TBTIPOSCOMPONENTESSAP(
	FITIPOCOMPONENTEID			INT 			IDENTITY(1,1),
	FIESTATUSID 				INT 			NOT NULL,
	FCNOMBRE 					VARCHAR(15) 	NOT NULL DEFAULT '-',
	FCDESCRIPCION				VARCHAR(150)	NOT NULL DEFAULT '-',
	CONSTRAINT PK_TBTIPOSCOMPONENTESSAP_01 PRIMARY KEY (FIMODELOPORUSUARIOID)
         WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
ON [PRIMARY]
GO